### ISSUE TITLE
Portal Loop Duplications: Governance proposal & Content Duplication in Gno.me on the Portal-Loop

### ISSUE THREAD

**Issue by michelleellen** [gnolang/gno#3478]
**Description**

There is a recurring issue with [Gno.me](http://gno.me/) in the Portal-Loop (PL) system where proposals are duplicated after transactions are re-run. This behavior was observed previously and is happening again.

1. Navigate to [[this link](https://gno.land/r/gnome/dao:proposals/council/ecosystem/community/tutorials?page=1)](https://gno.land/r/gnome/dao:proposals/council/ecosystem/community/tutorials?page=1). You can also see here than the news publication was published twice https://gno.land/r/gnome/space
2. Observe that proposals 7 and 8 are repeated.
    - Before the TX replay, the state was correct, and no duplication was present.
3. In this instance, proposals were created using Studio&Adena, not gnokey. However, a similar issue was observed when using gnokey.

**Additional Details**

- While creating the duplicated tutorial proposal, there was an issue with insufficient gas wanted.
    - Creating the proposal required several attempts (at least three failed transactions) until the correct gas value was set.
- From observations, the duplication seems to affect only the last [Gno.me](http://gno.me/) transaction during replay.
    - Previously, the last transaction was triplicated, suggesting randomness in the duplication behavior.
- This behavior results in unexpected duplication of proposals, leading to inconsistent states and potential governance issues.

**Updates**

On the core x devx call there was the Portal Loop replay process discussion, which may cause this to happen: When we perform a replay in the Portal Loop, the process involves placing transactions into the genesis file and replaying those genesis transactions without applying a gas limit. This approach has several important implications that @zivkovicmilos and @thehowl addressed (thanks for your sleuthing 😊)

1. Re-execution of Transactions
    - Transactions that would normally fail due to hitting the gas limit are executed successfully during the replay because the gas limit is removed.
    - Regardless of whether a transaction initially succeeded or failed, all transactions are replayed.
2. Duplication of Transactions
    - During the replay, each transaction is duplicated with different signatures.
    - For example, if one transaction succeeds, the PL may loop and duplicate that transaction multiple times (e.g., five times), creating repeated entries.
3. Execution Order
    - The order of transaction execution during the replay is not guaranteed, leading to potential inconsistencies in the order of transaction replays.

I hope this explains to some degree the issue and the brainstorming of possible reasons why it is happening. Feel free to add if I missed context. Thank you! 

cc @jeronimoalbi @moul @ilgooz

**Comment by moul** [comment]
It would be great for you to take this case as a way to confirm that the new gnodev-powered portal loop will be effective.

**Comment by gfanton** [comment]
My next focus will be on the `gnodev` for the portal loop. Currently, `gnodev` uses the same strategy and relies on the genesis to reload all transactions. However, it should definitely be possible to reload transactions without the genesis. I'm just a bit concerned about the performance and scalability of this approach.

**Comment by moul** [comment]
https://github.com/gnolang/gno/pull/3699 should fix this.
Maybe we'll need to cleanup PL history.

**Comment by leohhhn** [comment]
I see that the issue persists, like on the two realms below:
- https://gno.land/r/leon/fosdem25/microposts
- https://gno.land/r/gnome/dao:proposals/council/ecosystem/community/tutorials?page=1

So I assume we need to clean up the history, yes
